### Get all products
GET http://localhost:8080/api/products

### Get product by code
GET http://localhost:8080/api/products/P100

### Create a new order
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "customer": {
    "name": "Siva",
    "email": "siva@gmail.com",
    "phone": "90000123123"
  },
  "deliveryAddress": "Hyderabad",
  "item": {
    "code": "P100",
    "name": "Product 1",
    "price": "34.0",
    "quantity": 1
  }
}

### Get all orders
GET http://localhost:8080/api/orders

### Get orders by orderNumber
GET http://localhost:8080/api/orders/ORDER-100001
